package com.sisibibi.api.global.outbox;

public enum OutboxEventType {
  AI_REPORT_GENERATION_REQUESTED,
  AI_REPORT_PDF_GENERATION_REQUESTED,
  AI_REPORT_PDF_NOTIFICATION_REQUESTED,
  ACCOUNT_SUSPENSION_REFRESH_TOKEN_DELETE_REQUESTED
}