spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME:sisibibi}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:sisibibi}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:redis_1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false

app:
  auth:
    cookie:
      secure: true
      same-site: Lax
      domain: .issuetok.site


room-ranking:
  rebuild-on-startup: true